<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1522487007250" stop="1522487007350">
  <name>test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1522487007250" status="passed" stop="1522487007254">
      <name>TestLogin.test_login1</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9104-MainThread"/>
        <label name="host" value="DESKTOP-OFFSNT3"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1522487007255" status="failed" stop="1522487007348">
      <name>TestLogin.test_login2</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_login.TestLogin object at 0x00000216F56204E0&gt;

    def test_login2(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9104-MainThread"/>
        <label name="host" value="DESKTOP-OFFSNT3"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1522487007349" status="passed" stop="1522487007350">
      <name>TestLogin.test_login3</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="9104-MainThread"/>
        <label name="host" value="DESKTOP-OFFSNT3"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
